// <auto-generated />
namespace EscuelaACM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sambu001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sambu001));
        
        string IMigrationMetadata.Id
        {
            get { return "202302232234531_Sambu0.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
